services:
  text-embedding:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: text-embedding-service
    ports:
      - "8001:8000"
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

