services:

  chromadb:
    container_name: chromadb
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - ./chromadb:/data
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v2/heartbeat" ]
      interval: 30s
      timeout: 10s
      retries: 5
    # depends_on:
    #   - ollama
    # Chờ ollama
    external_links:
      - ollama
    networks:
      - strategy_net

networks:
  strategy_net:
    external: true
