[package]
name = "tank_ai"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
shared = { path = "../../crates/shared" }
serde = { workspace = true }
fastrand = { workspace = true }

[profile.release]
opt-level = 3
lto = true
