version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pgrag-pgvector
    environment:
      POSTGRES_DB: pgrag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres#2025
    ports:
      - "5432:5432"
    volumes:
      - ./pgvector_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build: .
    container_name: pgrag-app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: pgrag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres#2025
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

